; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

; Serial を USB CDC(GPIO 18/19) にルーティングし、UART0 による GPIO 20/21 の占有を回避する
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

; タイマー割り込み用の必須ライブラリを自動でダウンロードします [cite: 48, 49]
lib_deps = 
    khoih-prog/ESP32_C3_TimerInterrupt


monitor_speed = 19200
monitor_rts = 0
monitor_dtr = 0

